apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres2
  namespace: platform2-backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres2
  template:
    metadata:
      labels:
        app: postgres2
    spec:
      serviceAccountName: postgres3
      containers:
        - name: postgres2
          image: postgres:13.2-alpine
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres2-secrets